[project]
name = "dlrover"
version = "0.5.0.dev0+ray_unified"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "clipstick>=0.6.1",
    "deprecated",
    "grpcio",
    "omegaconf",
    "packaging",
    "psutil",
    "pydantic",
    "pynvml",
    "ray[default,train]",
    "requests",
    "tornado",
    "urllib3",
]

[dependency-groups]
dev = [
    "coverage>=7.9.2",
    "kubernetes>=33.1.0",
    "pytest>=8.4.1",
    "pytest-forked>=1.6.0",
    "transformers>=4.53.2",
]
torch = ["torch", "tensordict"]
